name: maplibre_ios
description: "Helper package for maplibre that provides iOS FFI bindings"
version: 0.0.1
homepage: https://github.com/josxha/flutter-maplibre

environment:
  flutter: ^3.29.0
  sdk: ^3.7.0

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  objective_c: ^7.0.0

dev_dependencies:
  ffigen: ^18.0.0
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MapLibreIosPlugin

ffigen:
  name: MapLibreFFi
  description: Bindings for MapLibre iOS.
  language: objc
  output: 'lib/maplibre_ffi.dart'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'NSString'
      - 'MapLibreRegistry'
      - 'MLNMapView'
      - 'MLNMapCamera'
      - 'CLLocationCoordinate2D'
      - 'MLNMapProjection'
      - 'MLNStyle'
      - 'MLNSource'
      - 'MLNRasterTileSource'
      - 'MLNVectorTileSource'
      - 'MLNImageSource'
      - 'MLNRasterDEMSource'
      - 'MLNVectorTileSource'
      - 'MLNBackgroundStyleLayer'
      - 'MLNStyleLayer'
      - 'MLNCircleStyleLayer'
      - 'MLNFillExtrusionStyleLayer'
      - 'MLNFillStyleLayer'
      - 'MLNHeatmapStyleLayer'
      - 'MLNHillshadeStyleLayer'
      - 'MLNLineStyleLayer'
      - 'MLNRasterStyleLayer'
      - 'MLNSymbolStyleLayer'
      - 'MLNVectorStyleLayer'
      - 'MLNAttributionInfo'
      - 'NSAttributedString'
      - 'MLNShapeSource'
      - 'MLNImageSource'
      - 'MLNMapViewDelegate'
      - 'MLNLocationManager'
      - 'MLNLocationManagerDelegate'
      - 'MLNGeometry'
      - 'MLNShape'
      - 'CLLocationDegrees'
      - 'MLNRasterDEMSource'
      - 'MLNOfflineStorage'
      - 'MLNTilePyramidOfflineRegion'
      - 'MLNOfflinePack'
      - 'MLNOfflineRegion'
      - 'MLNTilePyramidOfflineRegion'
      - 'NSImage'
      - 'NSExpression'
      - 'Helpers'
    module:
      'MapLibreRegistry': 'maplibre_ios'
      'Helpers': 'maplibre_ios'
      'MLNMapView': 'MapLibre'
      'MLNMapCamera': 'MapLibre'
      'MLNGeometry': 'MapLibre'
      'MLNVectorTileSource': 'MapLibre'
      'MLNOfflinePack': 'MapLibre'
      'MLNOfflineRegion': 'MapLibre'
      'MLNLocationManager': 'MapLibre'
  headers:
    entry-points:
      - 'ios/maplibre_ios/Sources/maplibre_ios/MapLibreRegistry.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNPolyline.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNFillExtrusionStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNVectorTileSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapCamera.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNUserLocationAnnotationViewStyle.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCustomStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNFoundation.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCalloutView.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCameraChangeReason.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNLoggingConfiguration.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/Mapbox.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNVectorStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCoordinateFormatter.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNTilePyramidOfflineRegion.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/NSValue+MLNAdditions.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNImageSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNTileServerOptions.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNShapeOfflineRegion.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNOverlay.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNClockDirectionFormatter.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapView+IBAdditions.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNFeature.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNNetworkConfiguration.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapProjection.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNSettings.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNStyleValue.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/NSPredicate+MLNAdditions.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNAttributedExpression.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCompassDirectionFormatter.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNLineStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNShapeCollection.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNForegroundStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNPolygon.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNHeatmapStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNRasterStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNRasterDEMSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNOfflineRegion.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCustomDrawableStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCluster.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNUserLocationAnnotationView.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNTileSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNRasterTileSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNBackgroundStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNBackendResource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNDefaultStyle.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNAnnotation.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNGeometry.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNOfflinePack.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNStyle.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNSymbolStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNLight.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNTypes.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MapLibre.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNAnnotationImage.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNComputedShapeSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNPointAnnotation.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNPointCollection.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapView.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/NSExpression+MLNAdditions.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMultiPoint.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNShapeSource.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCompassButton.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNLocationManager.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNDistanceFormatter.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapSnapshotter.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNUserLocation.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapViewDelegate.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNShape.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNFillStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCircleStyleLayer.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNScaleBar.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNAttributionInfo.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNOfflineStorage.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNAnnotationView.h'
      - './temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNHillshadeStyleLayer.h'

    # include-directives:
    #   - 'temp/MapLibre.dynamic.xcframework/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/'
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api
